version: '3.8'
services:
  postgres:
    image: postgres
    container_name: insurance_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: insurance
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: insurance_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: