spring:
  application:
    name: "insurance-quote"
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/insurance
    username: user
    password: pass
  datasource:
    url: jdbc:postgresql://localhost:5432/insurance
    username: user
    password: pass
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  main:
    allow-bean-definition-overriding: true