spring:
  application:
    name: "insurance-quote"
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/insurance
    username: user
    password: pass
  data:
    redis:
      host: localhost
      port: 6379
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: "Fj29kdP0sL9cmN7QwT8zxv1AyLq6Rb3K"