spring:
  application:
    name: "insurance-quote"
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: ${JWT_SECRET}